# Compose specification (https://github.com/compose-spec/compose-spec/blob/master/spec.md) as of Docker Compose 1.27.0+

# NOTE: This configuration assumes docker-compose is being run from the project's 'docker' folder.
# E.g.
#  > cd C:\path\to\project\docker
#  > docker compose up

# How to use the host's IP Address inside a Docker container
# see https://dev.to/natterstefan/docker-tip-how-to-get-host-s-ip-address-inside-a-docker-container-5anh#:~:text=On%20Docker%20for%20Linux%2C%20the,you%20are%20using%20default%20networking.

# Binding from Environment Variables
# https://docs.spring.io/spring-boot/docs/2.4.2/reference/htmlsingle/#boot-features-external-config-relaxed-binding-from-environment-variables

# 'automatic service discovery' in a user-defined network, allows containers to not only communicate by IP address,
# but they can also resolve a container name to an IP address
# https://docs.docker.com/network/network-tutorial-standalone/#use-user-defined-bridge-networks

# See currency-exchange-service/README.MD#"MySQL connection string" for information
# regarding the MySQL connection string

#services:
#  service-name:
#    deploy:
#      resources:
#        limits:
#          # https://github.com/compose-spec/compose-spec/blob/master/deploy.md#memory
#          memory: 1G
#    # https://github.com/compose-spec/compose-spec/blob/master/spec.md#ports
#    ports:
#      - "8000:8000"
#    # https://github.com/compose-spec/compose-spec/blob/master/spec.md#environment
#    environment:
#      RACK_ENV: development
#    # https://github.com/compose-spec/compose-spec/blob/master/spec.md#volumes
#    volumes:
#      volume:container:access_mode

services:
  currency-conversion:
    image: ibuttimer/ccm-currency-conversion-service:0.0.1-SNAPSHOT
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - "${CONVERT_PORT}:${CONVERT_PORT}"
    environment:
      MYSQL_CONVERSION_URL: //${DOCKER_GATEWAY_HOST:-host.docker.internal}:${MYSQL_PORT}/currency_conversion?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:${NAMING_PORT}/eureka
      CONFIG_SERVER_URL: http://spring-cloud-config-server:${CONFIG_PORT}/
      API_GATEWAY_URL: http://api-gateway:${API_PORT}/
      CURRENCY_EXCHANGE_URL: http://api-gateway:${API_PORT}/
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:${ZIPKIN_PORT}/
      RABBIT_URI: amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@rabbitmq:${RABBIT_PORT}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      TRACING_ENABLED: "true"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - spring-cloud-config-server
      - rabbitmq

  currency-exchange:
    image: ibuttimer/ccm-currency-exchange-service:0.0.1-SNAPSHOT
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - "${EXCHANGE_PORT}:${EXCHANGE_PORT}"
    environment:
      MYSQL_EXCHANGE_URL: //${DOCKER_GATEWAY_HOST:-host.docker.internal}:${MYSQL_PORT}/currency_exchange?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:${NAMING_PORT}/eureka
      CONFIG_SERVER_URL: http://spring-cloud-config-server:${CONFIG_PORT}/
      API_GATEWAY_URL: http://api-gateway:${API_PORT}/
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:${ZIPKIN_PORT}/
      RABBIT_URI: amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@rabbitmq:${RABBIT_PORT}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      TRACING_ENABLED: "true"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - spring-cloud-config-server
      - rabbitmq

  naming-server:
    image: ibuttimer/ccm-naming-server:0.0.1-SNAPSHOT
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "${NAMING_PORT}:${NAMING_PORT}"
    networks:
      - currency-network

  spring-cloud-config-server:
    image: ibuttimer/ccm-spring-cloud-config-server:0.0.1-SNAPSHOT
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "${CONFIG_PORT}:${CONFIG_PORT}"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:${NAMING_PORT}/eureka
      CONFIG_GIT_URI: file://git-localconfig-repo
    networks:
      - currency-network
    volumes:
      # map default project repository
      - ../git-localconfig-repo:/git-localconfig-repo
    depends_on:
      - naming-server

  api-gateway:
    image: ibuttimer/ccm-api-gateway:0.0.1-SNAPSHOT
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:${NAMING_PORT}/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:${ZIPKIN_PORT}/
      RABBIT_URI: amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@rabbitmq:${RABBIT_PORT}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      TRACING_ENABLED: "true"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq

  zipkin-server:
    image: openzipkin/zipkin
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - "${ZIPKIN_PORT}:${ZIPKIN_PORT}"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - currency-network
    environment:
      RABBIT_URI: amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@rabbitmq:${RABBIT_PORT}

  rabbitmq:
    image: rabbitmq:3.8.11-management
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 500M
    ports:
      - "${RABBIT_PORT}:${RABBIT_PORT}"           # AMQP connections
      - "${RABBIT_MGMT_PORT}:${RABBIT_MGMT_PORT}" # management port
    networks:
      - currency-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  currency-network: