# Compose specification (https://github.com/compose-spec/compose-spec/blob/master/spec.md) as of Docker Compose 1.27.0+

# NOTE: This configuration assumes docker-compose is being run from the project's 'docker' folder.
# E.g.
#  > cd C:\path\to\project\docker
#  > docker-compose up

# How to use the host's IP Address inside a Docker container
# see https://dev.to/natterstefan/docker-tip-how-to-get-host-s-ip-address-inside-a-docker-container-5anh#:~:text=On%20Docker%20for%20Linux%2C%20the,you%20are%20using%20default%20networking.

# Binding from Environment Variables
# https://docs.spring.io/spring-boot/docs/2.4.2/reference/htmlsingle/#boot-features-external-config-relaxed-binding-from-environment-variables

# 'automatic service discovery' in a user-defined network, allows containers to not only communicate by IP address,
# but they can also resolve a container name to an IP address
# https://docs.docker.com/network/network-tutorial-standalone/#use-user-defined-bridge-networks

#services:
#  service-name:
#    deploy:
#      resources:
#        limits:
#          # https://github.com/compose-spec/compose-spec/blob/master/deploy.md#memory
#          memory: 1G
#    # https://github.com/compose-spec/compose-spec/blob/master/spec.md#ports
#    ports:
#      - "8000:8000"
#    # https://github.com/compose-spec/compose-spec/blob/master/spec.md#environment
#    environment:
#      RACK_ENV: development
#    # https://github.com/compose-spec/compose-spec/blob/master/spec.md#volumes
#    volumes:
#      volume:container:access_mode

services:
  currency-conversion:
    image: ibuttimer/ccm-currency-conversion-service:0.0.1-SNAPSHOT-K
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - "8100:8100"
    environment:
      CURRENCY_EXCHANGE_URL: http://currency-exchange:8000/
    networks:
      - currency-network
    depends_on:
      - currency-exchange

  currency-exchange:
    image: ibuttimer/ccm-currency-exchange-service:0.0.1-SNAPSHOT-K
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - "8000:8000"
    networks:
      - currency-network

networks:
  currency-network: